
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Fixed fixed1;

	private global::Gtk.Label label3;

	private global::Gtk.Entry txtOutput;

	private global::Gtk.Button btnConvert;

	private global::Gtk.Label lblConvert;

	private global::Gtk.Entry txtInput;

	private global::Gtk.RadioButton btnReal;

	private global::Gtk.RadioButton btnFromReal;

	private global::Gtk.RadioButton btnFromEuro;

	private global::Gtk.RadioButton btnEuro;

	private global::Gtk.RadioButton btnDollar;

	private global::Gtk.RadioButton btnFromDollar;

	private global::Gtk.Label lblToggle1;

	private global::Gtk.Label lblToggle2;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Conversor de Moedas");
		this.Icon = global::Stetic.IconLoader.LoadIcon(this, "stock_smiley-15", global::Gtk.IconSize.Menu);
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.fixed1 = new global::Gtk.Fixed();
		this.fixed1.Name = "fixed1";
		this.fixed1.HasWindow = false;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.label3 = new global::Gtk.Label();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("*valores de conversão consultados às 9h do dia 13/08");
		this.fixed1.Add(this.label3);
		global::Gtk.Fixed.FixedChild w1 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.label3]));
		w1.X = 98;
		w1.Y = 325;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtOutput = new global::Gtk.Entry();
		this.txtOutput.CanFocus = true;
		this.txtOutput.Name = "txtOutput";
		this.txtOutput.IsEditable = false;
		this.txtOutput.InvisibleChar = '•';
		this.fixed1.Add(this.txtOutput);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtOutput]));
		w2.X = 180;
		w2.Y = 269;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnConvert = new global::Gtk.Button();
		this.btnConvert.CanFocus = true;
		this.btnConvert.Name = "btnConvert";
		this.btnConvert.UseUnderline = true;
		this.btnConvert.Label = "Converter";
		this.fixed1.Add(this.btnConvert);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnConvert]));
		w3.X = 226;
		w3.Y = 220;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblConvert = new global::Gtk.Label();
		this.lblConvert.Name = "lblConvert";
		this.lblConvert.LabelProp = global::Mono.Unix.Catalog.GetString("Converter:");
		this.fixed1.Add(this.lblConvert);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblConvert]));
		w4.X = 232;
		w4.Y = 49;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.txtInput = new global::Gtk.Entry();
		this.txtInput.CanFocus = true;
		this.txtInput.Name = "txtInput";
		this.txtInput.Text = global::Mono.Unix.Catalog.GetString("0");
		this.txtInput.IsEditable = true;
		this.txtInput.InvisibleChar = '•';
		this.fixed1.Add(this.txtInput);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.txtInput]));
		w5.X = 177;
		w5.Y = 82;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnReal = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Real"));
		this.btnReal.CanFocus = true;
		this.btnReal.Name = "btnReal";
		this.btnReal.DrawIndicator = true;
		this.btnReal.UseUnderline = true;
		this.btnReal.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed1.Add(this.btnReal);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnReal]));
		w6.X = 330;
		w6.Y = 164;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnFromReal = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Real"));
		this.btnFromReal.CanFocus = true;
		this.btnFromReal.Name = "btnFromReal";
		this.btnFromReal.DrawIndicator = true;
		this.btnFromReal.UseUnderline = true;
		this.btnFromReal.Group = new global::GLib.SList(global::System.IntPtr.Zero);
		this.fixed1.Add(this.btnFromReal);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnFromReal]));
		w7.X = 329;
		w7.Y = 135;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnFromEuro = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Euro"));
		this.btnFromEuro.CanFocus = true;
		this.btnFromEuro.Name = "btnFromEuro";
		this.btnFromEuro.DrawIndicator = true;
		this.btnFromEuro.UseUnderline = true;
		this.btnFromEuro.Group = this.btnFromReal.Group;
		this.fixed1.Add(this.btnFromEuro);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnFromEuro]));
		w8.X = 256;
		w8.Y = 135;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnEuro = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Euro"));
		this.btnEuro.CanFocus = true;
		this.btnEuro.Name = "btnEuro";
		this.btnEuro.DrawIndicator = true;
		this.btnEuro.UseUnderline = true;
		this.btnEuro.Group = this.btnReal.Group;
		this.fixed1.Add(this.btnEuro);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnEuro]));
		w9.X = 256;
		w9.Y = 164;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnDollar = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Dólar"));
		this.btnDollar.CanFocus = true;
		this.btnDollar.Name = "btnDollar";
		this.btnDollar.DrawIndicator = true;
		this.btnDollar.UseUnderline = true;
		this.btnDollar.Group = this.btnReal.Group;
		this.fixed1.Add(this.btnDollar);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnDollar]));
		w10.X = 183;
		w10.Y = 165;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.btnFromDollar = new global::Gtk.RadioButton(global::Mono.Unix.Catalog.GetString("Dólar"));
		this.btnFromDollar.CanFocus = true;
		this.btnFromDollar.Name = "btnFromDollar";
		this.btnFromDollar.DrawIndicator = true;
		this.btnFromDollar.UseUnderline = true;
		this.btnFromDollar.Group = this.btnFromReal.Group;
		this.fixed1.Add(this.btnFromDollar);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.btnFromDollar]));
		w11.X = 183;
		w11.Y = 134;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblToggle1 = new global::Gtk.Label();
		this.lblToggle1.Name = "lblToggle1";
		this.lblToggle1.LabelProp = global::Mono.Unix.Catalog.GetString("De:");
		this.fixed1.Add(this.lblToggle1);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblToggle1]));
		w12.X = 146;
		w12.Y = 136;
		// Container child fixed1.Gtk.Fixed+FixedChild
		this.lblToggle2 = new global::Gtk.Label();
		this.lblToggle2.Name = "lblToggle2";
		this.lblToggle2.LabelProp = global::Mono.Unix.Catalog.GetString("Para:");
		this.fixed1.Add(this.lblToggle2);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.fixed1[this.lblToggle2]));
		w13.X = 143;
		w13.Y = 168;
		this.Add(this.fixed1);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 537;
		this.DefaultHeight = 363;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.btnConvert.Clicked += new global::System.EventHandler(this.clickButton);
		this.btnFromReal.Toggled += new global::System.EventHandler(this.realOn);
		this.btnFromEuro.Toggled += new global::System.EventHandler(this.euroOn);
		this.btnFromDollar.Toggled += new global::System.EventHandler(this.dollarOn);
	}
}
